/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.seqera.tower.cli.credentials;

import io.seqera.tower.cli.BaseCmdTest;
import org.junit.jupiter.api.Test;
import org.mockserver.client.MockServerClient;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockserver.matchers.Times.exactly;
import static org.mockserver.model.HttpRequest.request;
import static org.mockserver.model.HttpResponse.response;

class CreateAwsCmdTest extends BaseCmdTest {

    @Test
    void testOnlyAssumeRole(MockServerClient mock) {

        // Create server expectation
        mock.when(
                request().withMethod("POST").withPath("/credentials").withBody("{\"credentials\":{\"name\":\"test_credentials\",\"provider\":\"aws\",\"keys\":{\"assumeRoleArn\":\"arn_role\"}}}"), exactly(1)
        ).respond(
                response().withStatusCode(200).withBody("{\"credentialsId\":\"6Kyn17toiABGu47qpBXsVX\"}")
        );

        // Run the command
        ExecOut out = exec(mock, "creds", "create", "aws", "--name=test_credentials", "--assume-role-arn=arn_role");

        // Assert results
        assertEquals("New AWS credentials 'test_credentials' added at personal workspace", out.stdOut);
        assertEquals("", out.stdErr);
        assertEquals(0, out.exitCode);

    }

}
