/*
 * Copyright 2021-2026, Seqera.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.seqera.tower.cli.data;

import com.fasterxml.jackson.core.JsonProcessingException;
import io.seqera.tower.cli.BaseCmdTest;
import io.seqera.tower.cli.commands.data.links.ListCmd;
import io.seqera.tower.cli.commands.enums.OutputType;
import io.seqera.tower.cli.exceptions.TowerRuntimeException;
import io.seqera.tower.cli.responses.data.DataLinkDeleted;
import io.seqera.tower.cli.responses.data.DataLinkFileTransferResult;
import io.seqera.tower.cli.responses.data.DataLinksList;
import io.seqera.tower.cli.utils.PaginationInfo;
import io.seqera.tower.model.DataLinkDto;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;
import org.junit.jupiter.params.provider.EnumSource;
import io.seqera.tower.model.DataLinkItemType;
import org.mockserver.client.MockServerClient;
import org.mockserver.model.Header;
import org.mockserver.model.MediaType;
import org.mockserver.verify.VerificationTimes;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import static io.seqera.tower.cli.utils.JsonHelper.parseJson;
import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockserver.matchers.Times.exactly;
import static org.mockserver.model.HttpRequest.request;
import static org.mockserver.model.HttpResponse.response;
import static org.mockserver.model.JsonBody.json;

public class DataLinksCmdTest extends BaseCmdTest {

    @BeforeEach
    void init(MockServerClient mock) {
        mock.reset();
    }

    @ParameterizedTest
    @CsvSource(delimiter = ';', value = {
            "bucket-name;aws;eu-west-1;s3://some-bucket/is/path;bucket-name provider:aws region:eu-west-1 resourceRef:s3://some-bucket/is/path",
            ";aws,azure;eu-west-1;;provider:aws,azure region:eu-west-1",
            ";google;;;provider:google",
            ";;;;"
    })
    void testBuildingSearchParameter(String name, String providers, String region, String uri, String expected) {
        String result = ListCmd.buildSearch(name, providers, region, uri);
        assertEquals(result, expected);
    }

    @ParameterizedTest
    @EnumSource(OutputType.class)
    void testList(OutputType format, MockServerClient mock) throws JsonProcessingException {
        // credentials fetch
        mock.when(
                request().withMethod("GET").withPath("/credentials").withQueryStringParameter("workspaceId", "75887156211589"), exactly(1)
        ).respond(
                response().withStatusCode(200).withBody("{\"credentials\":[{\"id\":\"57Ic6reczFn78H1DTaaXkp\",\"name\":\"aws\",\"description\":null,\"discriminator\":\"aws\",\"baseUrl\":null,\"category\":null,\"deleted\":null,\"lastUsed\":\"2021-09-09T07:20:53Z\",\"dateCreated\":\"2021-09-08T05:48:51Z\",\"lastUpdated\":\"2021-09-08T05:48:51Z\"}]}").withContentType(MediaType.APPLICATION_JSON)
        );
        // status check
        mock.when(
                request()
                        .withMethod("GET").withPath("/data-links")
                        .withQueryStringParameter("workspaceId", "75887156211589")
                        .withQueryStringParameter("offset", "0")
                        .withQueryStringParameter("max", "1"),
                exactly(1)
        ).respond(
                response().withStatusCode(200).withBody(loadResource("data/links/datalinks_list")).withContentType(MediaType.APPLICATION_JSON)
        );
        // mock fetch data links
        mock.when(
                request()
                        .withMethod("GET").withPath("/data-links")
                        .withQueryStringParameter("workspaceId", "75887156211589")
                        .withQueryStringParameter("offset", "0")
                        .withQueryStringParameter("max", "100"),
                exactly(1)
        ).respond(
                response().withStatusCode(200).withBody(loadResource("data/links/datalinks_list")).withContentType(MediaType.APPLICATION_JSON)
        );

        mock.when(
                request().withMethod("GET").withPath("/user-info"), exactly(1)
        ).respond(
                response().withStatusCode(200).withBody(loadResource("user")).withContentType(MediaType.APPLICATION_JSON)
        );

        mock.when(
                request().withMethod("GET").withPath("/user/1264/workspaces"), exactly(1)
        ).respond(
                response().withStatusCode(200).withBody(loadResource("workspaces/workspaces_list")).withContentType(MediaType.APPLICATION_JSON)
        );

        ExecOut out = exec(format, mock, "data-links", "list", "-w", "75887156211589");

        // No errors thrown
        assertEquals("", out.stdErr);
        assertEquals(0, out.exitCode);

        assertOutput(format, out, new DataLinksList("[organization1 / workspace1]",
                Arrays.asList(
                        parseJson("{\n" +
                                "      \"id\": \"v1-cloud-c2875f38a7b5c8fe34a5b382b5f9e0c4\",\n" +
                                "      \"name\": \"a-test-bucket-eend-us-east-1\",\n" +
                                "      \"description\": null,\n" +
                                "      \"resourceRef\": \"s3://a-test-bucket-eend-us-east-1\",\n" +
                                "      \"type\": \"bucket\",\n" +
                                "      \"provider\": \"aws\",\n" +
                                "      \"region\": \"us-east-1\",\n" +
                                "      \"credentials\": [\n" +
                                "        {\n" +
                                "          \"id\": \"57Ic6reczFn78H1DTaaXkp\",\n" +
                                "          \"name\": \"aws\",\n" +
                                "          \"provider\": \"aws\"\n" +
                                "        }\n" +
                                "      ],\n" +
                                "      \"publicAccessible\": false,\n" +
                                "      \"hidden\": false,\n" +
                                "      \"status\": null,\n" +
                                "      \"message\": null\n" +
                                "    }", DataLinkDto.class),
                        parseJson("{\n" +
                                "      \"id\": \"v1-cloud-b89b60014c225c11f59048294354d174\",\n" +
                                "      \"name\": \"adrian-navarro-test\",\n" +
                                "      \"description\": null,\n" +
                                "      \"resourceRef\": \"s3://adrian-navarro-test\",\n" +
                                "      \"type\": \"bucket\",\n" +
                                "      \"provider\": \"aws\",\n" +
                                "      \"region\": \"us-east-1\",\n" +
                                "      \"credentials\": [\n" +
                                "        {\n" +
                                "          \"id\": \"57Ic6reczFn78H1DTaaXkp\",\n" +
                                "          \"name\": \"aws\",\n" +
                                "          \"provider\": \"aws\"\n" +
                                "        }\n" +
                                "      ],\n" +
                                "      \"publicAccessible\": false,\n" +
                                "      \"hidden\": false,\n" +
                                "      \"status\": null,\n" +
                                "      \"message\": null\n" +
                                "    }", DataLinkDto.class),
                        parseJson("{\n" +
                                "      \"id\": \"v1-cloud-422306eddadfc64de0676a5923517733\",\n" +
                                "      \"name\": \"adrian-navarro-test-us-west-2\",\n" +
                                "      \"description\": null,\n" +
                                "      \"resourceRef\": \"s3://adrian-navarro-test-us-west-2\",\n" +
                                "      \"type\": \"bucket\",\n" +
                                "      \"provider\": \"aws\",\n" +
                                "      \"region\": \"us-west-2\",\n" +
                                "      \"credentials\": [\n" +
                                "        {\n" +
                                "          \"id\": \"57Ic6reczFn78H1DTaaXkp\",\n" +
                                "          \"name\": \"aws\",\n" +
                                "          \"provider\": \"aws\"\n" +
                                "        }\n" +
                                "      ],\n" +
                                "      \"publicAccessible\": false,\n" +
                                "      \"hidden\": false,\n" +
                                "      \"status\": null,\n" +
                                "      \"message\": null\n" +
                                "    }", DataLinkDto.class)
                ), false, PaginationInfo.from(0, 100)));
    }

    @ParameterizedTest
    @EnumSource(OutputType.class)
    void testFilteredList(OutputType format, MockServerClient mock) throws JsonProcessingException {
        String json = "{\n" +
                "      \"id\": \"v1-cloud-b89b60014c225c11f59048294354d174\",\n" +
                "      \"name\": \"adrian-navarro-test\",\n" +
                "      \"description\": null,\n" +
                "      \"resourceRef\": \"s3://adrian-navarro-test\",\n" +
                "      \"type\": \"bucket\",\n" +
                "      \"provider\": \"aws\",\n" +
                "      \"region\": \"us-east-1\",\n" +
                "      \"credentials\": [\n" +
                "        {\n" +
                "          \"id\": \"57Ic6reczFn78H1DTaaXkp\",\n" +
                "          \"name\": \"aws\",\n" +
                "          \"provider\": \"aws\"\n" +
                "        }\n" +
                "      ],\n" +
                "      \"publicAccessible\": false,\n" +
                "      \"hidden\": false,\n" +
                "      \"status\": null,\n" +
                "      \"message\": null\n" +
                "    }";

        // credentials fetch
        mock.when(
                request().withMethod("GET").withPath("/credentials").withQueryStringParameter("workspaceId", "75887156211589"), exactly(1)
        ).respond(
                response().withStatusCode(200).withBody("{\"credentials\":[{\"id\":\"57Ic6reczFn78H1DTaaXkp\",\"name\":\"aws\",\"description\":null,\"discriminator\":\"aws\",\"baseUrl\":null,\"category\":null,\"deleted\":null,\"lastUsed\":\"2021-09-09T07:20:53Z\",\"dateCreated\":\"2021-09-08T05:48:51Z\",\"lastUpdated\":\"2021-09-08T05:48:51Z\"}]}").withContentType(MediaType.APPLICATION_JSON)
        );
        // status check
        mock.when(
                request()
                        .withMethod("GET").withPath("/data-links")
                        .withQueryStringParameter("workspaceId", "75887156211589")
                        .withQueryStringParameter("offset", "0")
                        .withQueryStringParameter("max", "1"),
                exactly(1)
        ).respond(
                response().withStatusCode(200).withBody(loadResource("data/links/datalinks_list")).withContentType(MediaType.APPLICATION_JSON)
        );
        // mock fetch data links
        mock.when(
                request()
                        .withMethod("GET").withPath("/data-links")
                        .withQueryStringParameter("workspaceId", "75887156211589")
                        .withQueryStringParameter("search", "adrian provider:aws region:us-east-1")
                        .withQueryStringParameter("offset", "0")
                        .withQueryStringParameter("max", "100"),
                exactly(1)
        ).respond(
                response().withStatusCode(200).withBody("{\"dataLinks\": [" + json + "] }").withContentType(MediaType.APPLICATION_JSON)
        );

        mock.when(
                request().withMethod("GET").withPath("/user-info"), exactly(1)
        ).respond(
                response().withStatusCode(200).withBody(loadResource("user")).withContentType(MediaType.APPLICATION_JSON)
        );

        mock.when(
                request().withMethod("GET").withPath("/user/1264/workspaces"), exactly(1)
        ).respond(
                response().withStatusCode(200).withBody(loadResource("workspaces/workspaces_list")).withContentType(MediaType.APPLICATION_JSON)
        );

        ExecOut out = exec(format, mock, "data-links", "list", "-w", "75887156211589", "-n", "adrian", "-p", "aws", "-r", "us-east-1");

        // No errors thrown
        assertEquals("", out.stdErr);
        assertEquals(0, out.exitCode);

        assertOutput(format, out,
                new DataLinksList(
                        "[organization1 / workspace1]",
                        Collections.singletonList(parseJson(json, DataLinkDto.class)),
                        false,
                        PaginationInfo.from(0, 100)
                )
        );
    }

    @ParameterizedTest
    @EnumSource(OutputType.class)
    void testAdd(OutputType format, MockServerClient mock) throws JsonProcessingException {
        // credentials fetch
        mock.when(
                request().withMethod("GET").withPath("/credentials").withQueryStringParameter("workspaceId", "75887156211589"), exactly(1)
        ).respond(
                response().withStatusCode(200).withBody("{\"credentials\":[{\"id\":\"57Ic6reczFn78H1DTaaXkp\",\"name\":\"aws\",\"description\":null,\"discriminator\":\"aws\",\"baseUrl\":null,\"category\":null,\"deleted\":null,\"lastUsed\":\"2021-09-09T07:20:53Z\",\"dateCreated\":\"2021-09-08T05:48:51Z\",\"lastUpdated\":\"2021-09-08T05:48:51Z\"}]}").withContentType(MediaType.APPLICATION_JSON)
        );
        // status check
        mock.when(
                request()
                        .withMethod("POST").withPath("/data-links")
                        .withQueryStringParameter("workspaceId", "75887156211589")
                        .withBody(json("{\n" +
                                "   \"name\":\"name\",\n" +
                                "   \"description\":\"somedesc\",\n" +
                                "   \"type\":\"bucket\",\n" +
                                "   \"provider\":\"aws\",\n" +
                                "   \"resourceRef\":\"s3://bucket\",\n" +
                                "   \"publicAccessible\":false,\n" +
                                "   \"credentialsId\":\"57Ic6reczFn78H1DTaaXkp\"\n" +
                                "}")),
                exactly(1)
        ).respond(
                response().withStatusCode(200).withBody("{\n" +
                        "    \"id\": \"v1-user-ad5192871d3d65e1218ec6c4a2f7cde5\",\n" +
                        "    \"name\": \"name\",\n" +
                        "    \"description\": \"somedesc\",\n" +
                        "    \"resourceRef\": \"s3://bucket\",\n" +
                        "    \"type\": \"bucket\",\n" +
                        "    \"provider\": \"aws\",\n" +
                        "    \"region\": \"us-east-1\",\n" +
                        "    \"credentials\": [\n" +
                        "        {\n" +
                        "            \"id\": \"57Ic6reczFn78H1DTaaXkp\",\n" +
                        "            \"name\": \"aws\",\n" +
                        "            \"provider\": \"aws\"\n" +
                        "        }\n" +
                        "    ],\n" +
                        "    \"publicAccessible\": false,\n" +
                        "    \"hidden\": false,\n" +
                        "    \"status\": null,\n" +
                        "    \"message\": null\n" +
                        "}").withContentType(MediaType.APPLICATION_JSON)
        );

        ExecOut out = exec(format, mock, "data-links", "add", "-w", "75887156211589", "-n", "name", "-d", "somedesc", "-p", "aws",
                "-u", "s3://bucket", "-c", "57Ic6reczFn78H1DTaaXkp");

        // No errors thrown
        assertEquals("", out.stdErr);
        assertEquals(0, out.exitCode);
    }

    @ParameterizedTest
    @EnumSource(OutputType.class)
    void testDelete(OutputType format, MockServerClient mock) {
        mock.when(
                request().withMethod("DELETE").withPath("/data-links/v1-datalinkid")
                        .withQueryStringParameter("workspaceId", "75887156211589"),
                exactly(1)
        ).respond(
                response().withStatusCode(200)
        );

        ExecOut out = exec(format, mock, "data-links", "delete", "-w", "75887156211589", "-i", "v1-datalinkid");

        assertOutput(format, out, new DataLinkDeleted("v1-datalinkid", 75887156211589L));
    }

    @ParameterizedTest
    @EnumSource(OutputType.class)
    void testUpdate(OutputType format, MockServerClient mock) {
        // credentials fetch
        mock.when(
                request().withMethod("GET").withPath("/credentials").withQueryStringParameter("workspaceId", "75887156211589"), exactly(1)
        ).respond(
                response().withStatusCode(200).withBody("{\"credentials\":[{\"id\":\"57Ic6reczFn78H1DTaaXkp\",\"name\":\"aws\",\"description\":null,\"discriminator\":\"aws\",\"baseUrl\":null,\"category\":null,\"deleted\":null,\"lastUsed\":\"2021-09-09T07:20:53Z\",\"dateCreated\":\"2021-09-08T05:48:51Z\",\"lastUpdated\":\"2021-09-08T05:48:51Z\"}]}").withContentType(MediaType.APPLICATION_JSON)
        );
        // status check
        mock.when(
                request()
                        .withMethod("PUT").withPath("/data-links/v1-somedatalinkid")
                        .withQueryStringParameter("workspaceId", "75887156211589")
                        .withBody(json("{\n" +
                                "   \"name\":\"name\",\n" +
                                "   \"description\":\"somedesc\",\n" +
                                "   \"credentialsId\":\"57Ic6reczFn78H1DTaaXkp\"\n" +
                                "}")),
                exactly(1)
        ).respond(
                response().withStatusCode(200).withBody("{\n" +
                        "    \"id\": \"v1-user-ad5192871d3d65e1218ec6c4a2f7cde5\",\n" +
                        "    \"name\": \"name\",\n" +
                        "    \"description\": \"somedesc\",\n" +
                        "    \"resourceRef\": \"s3://bucket\",\n" +
                        "    \"type\": \"bucket\",\n" +
                        "    \"provider\": \"aws\",\n" +
                        "    \"region\": \"us-east-1\",\n" +
                        "    \"credentials\": [\n" +
                        "        {\n" +
                        "            \"id\": \"57Ic6reczFn78H1DTaaXkp\",\n" +
                        "            \"name\": \"aws\",\n" +
                        "            \"provider\": \"aws\"\n" +
                        "        }\n" +
                        "    ],\n" +
                        "    \"publicAccessible\": false,\n" +
                        "    \"hidden\": false,\n" +
                        "    \"status\": null,\n" +
                        "    \"message\": null\n" +
                        "}").withContentType(MediaType.APPLICATION_JSON)
        );

        ExecOut out = exec(format, mock, "data-links", "update", "-w", "75887156211589", "-i", "v1-somedatalinkid", "-n", "name", "-d", "somedesc", "-c", "57Ic6reczFn78H1DTaaXkp");

        // No errors thrown
        assertEquals("", out.stdErr);
        assertEquals(0, out.exitCode);
    }

    @ParameterizedTest
    @EnumSource(OutputType.class)
    void testBrowse(OutputType format, MockServerClient mock) {
        // credentials fetch
        mock.when(
                request().withMethod("GET").withPath("/credentials").withQueryStringParameter("workspaceId", "75887156211589"), exactly(1)
        ).respond(
                response().withStatusCode(200).withBody("{\"credentials\":[{\"id\":\"57Ic6reczFn78H1DTaaXkp\",\"name\":\"aws\",\"description\":null,\"discriminator\":\"aws\",\"baseUrl\":null,\"category\":null,\"deleted\":null,\"lastUsed\":\"2021-09-09T07:20:53Z\",\"dateCreated\":\"2021-09-08T05:48:51Z\",\"lastUpdated\":\"2021-09-08T05:48:51Z\"}]}").withContentType(MediaType.APPLICATION_JSON)
        );
        mock.when(
                request()
                        .withMethod("GET").withPath("/data-links/v1-somedatalinkid")
                        .withQueryStringParameter("workspaceId", "75887156211589")
                        .withQueryStringParameter("credentialsId", "57Ic6reczFn78H1DTaaXkp"),
                exactly(1)
        ).respond(
                response().withStatusCode(200).withBody("{\n" +
                        "    \"dataLink\": {\n" +
                        "        \"id\": \"v1-cloud-9beb9b921331ce1427d23bd62ac4c4f7\",\n" +
                        "        \"name\": \"adrian-navarro-test\",\n" +
                        "        \"description\": null,\n" +
                        "        \"resourceRef\": \"s3://adrian-navarro-test\",\n" +
                        "        \"type\": \"bucket\",\n" +
                        "        \"provider\": \"aws\",\n" +
                        "        \"region\": \"us-east-1\",\n" +
                        "        \"credentials\": [\n" +
                        "            {\n" +
                        "                \"id\": \"5EXFx2R5zWuwYtpKHhCZ0X\",\n" +
                        "                \"name\": \"seqera_aws\",\n" +
                        "                \"provider\": \"aws\"\n" +
                        "            }\n" +
                        "        ],\n" +
                        "        \"publicAccessible\": false,\n" +
                        "        \"hidden\": false,\n" +
                        "        \"status\": null,\n" +
                        "        \"message\": null\n" +
                        "    }\n" +
                        "}").withContentType(MediaType.APPLICATION_JSON)
        );

        mock.when(
                request()
                        .withMethod("GET").withPath("/data-links/v1-somedatalinkid/browse/path")
                        .withQueryStringParameter("workspaceId", "75887156211589")
                        .withQueryStringParameter("credentialsId", "57Ic6reczFn78H1DTaaXkp")
                        .withQueryStringParameter("search", "name")
                        .withQueryStringParameter("nextPageToken", "sometoken")
                        .withQueryStringParameter("pageSize", "1"),
                exactly(1)
        ).respond(
                response().withStatusCode(200).withBody("{\n" +
                        "    \"originalPath\": \"s3://adrian-navarro-test/lambda_tutorial_adrian\",\n" +
                        "    \"objects\": [\n" +
                        "        {\n" +
                        "            \"type\": \"FILE\",\n" +
                        "            \"name\": \"test4.csv\",\n" +
                        "            \"size\": 1286,\n" +
                        "            \"mimeType\": \"text/csv\"\n" +
                        "        }\n" +
                        "    ],\n" +
                        "    \"nextPageToken\": null\n" +
                        "}").withContentType(MediaType.APPLICATION_JSON)
        );

        ExecOut out = exec(format, mock, "data-links", "browse", "-w", "75887156211589", "-i", "v1-somedatalinkid", "-f", "name", "-p", "path",
                "-c", "57Ic6reczFn78H1DTaaXkp", "-t", "sometoken", "--page", "1");

        // No errors thrown
        assertEquals("", out.stdErr);
        assertEquals(0, out.exitCode);
    }

    // Only run this test in json output format, since extra stdout output is printed out to console for download progress bar
    @ParameterizedTest
    @EnumSource(value = OutputType.class, names = {"json"})
    void testDownloadSingleFile(OutputType format, MockServerClient mock) throws IOException {
        // credentials fetch
        mock.when(
                request().withMethod("GET").withPath("/credentials").withQueryStringParameter("workspaceId", "75887156211589"), exactly(1)
        ).respond(
                response().withStatusCode(200).withBody("{\"credentials\":[{\"id\":\"57Ic6reczFn78H1DTaaXkp\",\"name\":\"aws\",\"description\":null,\"discriminator\":\"aws\",\"baseUrl\":null,\"category\":null,\"deleted\":null,\"lastUsed\":\"2021-09-09T07:20:53Z\",\"dateCreated\":\"2021-09-08T05:48:51Z\",\"lastUpdated\":\"2021-09-08T05:48:51Z\"}]}").withContentType(MediaType.APPLICATION_JSON)
        );

        // status check
        mock.when(
                request()
                        .withMethod("GET").withPath("/data-links")
                        .withQueryStringParameter("workspaceId", "75887156211589")
                        .withQueryStringParameter("offset", "0")
                        .withQueryStringParameter("max", "1"),
                exactly(1)
        ).respond(
                response().withStatusCode(200).withBody(loadResource("data/links/datalinks_list")).withContentType(MediaType.APPLICATION_JSON)
        );
        // mock fetch data links list
        mock.when(
                request().withMethod("GET").withPath("/data-links")
                        .withQueryStringParameter("workspaceId", "75887156211589")
                        .withQueryStringParameter("search", "a-test-bucket-eend-us-east-1"), exactly(1)
        ).respond(
                response().withStatusCode(200).withBody(loadResource("data/links/datalinks_list")).withContentType(MediaType.APPLICATION_JSON)
        );

        // mock fetching the path tree
        mock.when(
                request().withMethod("GET").withPath("/data-links/v1-cloud-c2875f38a7b5c8fe34a5b382b5f9e0c4/browse-tree")
                        .withQueryStringParameter("workspaceId", "75887156211589")
                        .withQueryStringParameter("credentialsId", "57Ic6reczFn78H1DTaaXkp")
                        .withQueryStringParameter("paths", "directory/filename.txt"), exactly(1)
        ).respond(
                response().withStatusCode(200).withBody(json("""
                            {
                                 "items": []
                             }"""
                )).withContentType(MediaType.APPLICATION_JSON)
        );

        mock.when(
                request()
                        .withMethod("GET").withPath("/data-links/v1-cloud-c2875f38a7b5c8fe34a5b382b5f9e0c4/generate-download-url")
                        .withQueryStringParameter("filePath", "directory/filename.txt")
                        .withQueryStringParameter("preview", "false")
                        .withQueryStringParameter("workspaceId", "75887156211589")
                        .withQueryStringParameter("credentialsId", "57Ic6reczFn78H1DTaaXkp"),
                exactly(1)
        ).respond(
                response().withStatusCode(200).withBody("{\n" +
                        "    \"url\": \"http://localhost:"+mock.getPort()+"/download/directory/filename.txt\"\n" +
                        "}").withContentType(MediaType.APPLICATION_JSON)
        );

        byte[] fileContent = "Mock file content".getBytes();
        String filename = "filename.txt";
        mock.when(
                request()
                        .withMethod("GET").withPath("/download/directory/filename.txt"),
                exactly(1)
        ).respond(
                response()
                        .withStatusCode(200)
                        .withHeader(new Header("Content-Type", "application/octet-stream"))
                        .withHeader(new Header("Content-Disposition", "attachment; filename=\"" + filename + "\""))
                        .withHeader(new Header("Content-Length", String.valueOf(fileContent.length)))
                        .withBody(fileContent)
        );

        ExecOut out = exec(format, mock, "data-links", "download", "-w", "75887156211589", "-n", "a-test-bucket-eend-us-east-1", "-c", "57Ic6reczFn78H1DTaaXkp",
                "--output-dir", tempDir().toString(), "directory/filename.txt");

        assertOutput(format, out, DataLinkFileTransferResult.donwloaded(List.of(new DataLinkFileTransferResult.SimplePathInfo(DataLinkItemType.FILE,  "directory/filename.txt", 1))));

        // verify the API has been polled additionally for the status
        mock.verify(request().withMethod("GET").withPath("/download/directory/filename.txt"), VerificationTimes.exactly(1));

        Path outputPath = tempDir().resolve(filename);

        assertTrue(Files.exists(outputPath));
        byte[] actualBytes = Files.readAllBytes(outputPath);
        assertArrayEquals(fileContent, actualBytes);
        Files.deleteIfExists(outputPath);

        // No errors thrown
        assertEquals("", out.stdErr);
        assertEquals(0, out.exitCode);
    }


    // Only run this test in json output format, since extra stdout output is printed out to console for download progress bar
    @ParameterizedTest
    @EnumSource(value = OutputType.class, names = {"json"})
    void testDownloadDirectory(OutputType format, MockServerClient mock) throws IOException {
        // credentials fetch
        mock.when(
                request().withMethod("GET").withPath("/credentials").withQueryStringParameter("workspaceId", "75887156211589"), exactly(1)
        ).respond(
                response().withStatusCode(200).withBody("{\"credentials\":[{\"id\":\"57Ic6reczFn78H1DTaaXkp\",\"name\":\"aws\",\"description\":null,\"discriminator\":\"aws\",\"baseUrl\":null,\"category\":null,\"deleted\":null,\"lastUsed\":\"2021-09-09T07:20:53Z\",\"dateCreated\":\"2021-09-08T05:48:51Z\",\"lastUpdated\":\"2021-09-08T05:48:51Z\"}]}").withContentType(MediaType.APPLICATION_JSON)
        );

        // status check
        mock.when(
                request()
                        .withMethod("GET").withPath("/data-links")
                        .withQueryStringParameter("workspaceId", "75887156211589")
                        .withQueryStringParameter("offset", "0")
                        .withQueryStringParameter("max", "1"),
                exactly(1)
        ).respond(
                response().withStatusCode(200).withBody(loadResource("data/links/datalinks_list")).withContentType(MediaType.APPLICATION_JSON)
        );
        // mock fetch data links list
        mock.when(
                request().withMethod("GET").withPath("/data-links")
                        .withQueryStringParameter("workspaceId", "75887156211589")
                        .withQueryStringParameter("search", "a-test-bucket-eend-us-east-1"), exactly(1)
        ).respond(
                response().withStatusCode(200).withBody(loadResource("data/links/datalinks_list")).withContentType(MediaType.APPLICATION_JSON)
        );

        byte[] fileContent1 = "Mock file content 1".getBytes();
        byte[] fileContent2 = "Mock file content 2".getBytes();
        String filename1 = "filename1.txt";
        String filename2 = "filename2.txt";

        mock.when(
                request().withMethod("GET").withPath("/data-links/v1-cloud-c2875f38a7b5c8fe34a5b382b5f9e0c4/browse-tree")
                        .withQueryStringParameter("workspaceId", "75887156211589")
                        .withQueryStringParameter("credentialsId", "57Ic6reczFn78H1DTaaXkp")
                        .withQueryStringParameter("paths", "directory/"), exactly(1)
        ).respond(
                response().withStatusCode(200).withBody(json("""
                            {
                                 "items": [
                                         {
                                             "path": "directory/filename1.txt",
                                             "size": 106421
                                         },
                                         {
                                             "path": "directory/subdirectory/filename2.txt",
                                             "size": 106421
                                         }
                                 ]
                             }"""
                )).withContentType(MediaType.APPLICATION_JSON)
        );

        // request to download file 1
        mock.when(
                request()
                        .withMethod("GET").withPath("/data-links/v1-cloud-c2875f38a7b5c8fe34a5b382b5f9e0c4/generate-download-url")
                        .withQueryStringParameter("filePath", "directory/" + filename1)
                        .withQueryStringParameter("preview", "false")
                        .withQueryStringParameter("workspaceId", "75887156211589")
                        .withQueryStringParameter("credentialsId", "57Ic6reczFn78H1DTaaXkp"),
                exactly(1)
        ).respond(
                response().withStatusCode(200).withBody("{\n" +
                        "    \"url\": \"http://localhost:"+mock.getPort()+"/download/directory/"+filename1+"\"\n" +
                        "}").withContentType(MediaType.APPLICATION_JSON)
        );

        mock.when(
                request()
                        .withMethod("GET").withPath("/download/directory/"+filename1),
                exactly(1)
        ).respond(
                response()
                        .withStatusCode(200)
                        .withHeader(new Header("Content-Type", "application/octet-stream"))
                        .withHeader(new Header("Content-Disposition", "attachment; filename=\"" + filename1 + "\""))
                        .withHeader(new Header("Content-Length", String.valueOf(fileContent1.length)))
                        .withBody(fileContent1)
        );

        // request to download file 2
        mock.when(
                request()
                        .withMethod("GET").withPath("/data-links/v1-cloud-c2875f38a7b5c8fe34a5b382b5f9e0c4/generate-download-url")
                        .withQueryStringParameter("filePath", "directory/subdirectory/" + filename2)
                        .withQueryStringParameter("preview", "false")
                        .withQueryStringParameter("workspaceId", "75887156211589")
                        .withQueryStringParameter("credentialsId", "57Ic6reczFn78H1DTaaXkp"),
                exactly(1)
        ).respond(
                response().withStatusCode(200).withBody("{\n" +
                        "    \"url\": \"http://localhost:"+mock.getPort()+"/download/directory/subdirectory/"+filename2+"\"\n" +
                        "}").withContentType(MediaType.APPLICATION_JSON)
        );

        mock.when(
                request()
                        .withMethod("GET").withPath("/download/directory/subdirectory/"+filename2),
                exactly(1)
        ).respond(
                response()
                        .withStatusCode(200)
                        .withHeader(new Header("Content-Type", "application/octet-stream"))
                        .withHeader(new Header("Content-Disposition", "attachment; filename=\"" + filename2 + "\""))
                        .withHeader(new Header("Content-Length", String.valueOf(fileContent2.length)))
                        .withBody(fileContent2)
        );

        ExecOut out = exec(format, mock, "data-links", "download", "-w", "75887156211589", "-n", "a-test-bucket-eend-us-east-1", "-c", "57Ic6reczFn78H1DTaaXkp",
                "--output-dir", tempDir().toString(), "directory/");

        assertOutput(format, out, DataLinkFileTransferResult.donwloaded(List.of(new DataLinkFileTransferResult.SimplePathInfo(DataLinkItemType.FOLDER, "directory/", 2))));

        // verify the API has been polled additionally for the status
        mock.verify(request().withMethod("GET").withPath("/download/directory/"+filename1), VerificationTimes.exactly(1));
        mock.verify(request().withMethod("GET").withPath("/download/directory/subdirectory/"+filename2), VerificationTimes.exactly(1));

        Path outputPath1 = tempDir().resolve("directory/"+filename1);
        Path outputPath2 = tempDir().resolve("directory/subdirectory/"+filename2);

        assertTrue(Files.exists(outputPath1));
        assertTrue(Files.exists(outputPath2));
        byte[] actualBytes1 = Files.readAllBytes(outputPath1);
        byte[] actualBytes2 = Files.readAllBytes(outputPath2);
        assertArrayEquals(fileContent1, actualBytes1);
        assertArrayEquals(fileContent2, actualBytes2);
        Files.deleteIfExists(outputPath1);
        Files.deleteIfExists(outputPath2);

        // No errors thrown
        assertEquals("", out.stdErr);
        assertEquals(0, out.exitCode);
    }

    @ParameterizedTest
    @EnumSource(value = OutputType.class, names = {"json"})
    void testUploadSingleFile(OutputType format, MockServerClient mock) throws IOException {
        // credentials fetch
        mock.when(
                request().withMethod("GET").withPath("/credentials").withQueryStringParameter("workspaceId", "75887156211589"), exactly(1)
        ).respond(
                response().withStatusCode(200).withBody("{\"credentials\":[{\"id\":\"57Ic6reczFn78H1DTaaXkp\",\"name\":\"aws\",\"description\":null,\"discriminator\":\"aws\",\"baseUrl\":null,\"category\":null,\"deleted\":null,\"lastUsed\":\"2021-09-09T07:20:53Z\",\"dateCreated\":\"2021-09-08T05:48:51Z\",\"lastUpdated\":\"2021-09-08T05:48:51Z\"}]}").withContentType(MediaType.APPLICATION_JSON)
        );

        // status check
        mock.when(
                request()
                        .withMethod("GET").withPath("/data-links")
                        .withQueryStringParameter("workspaceId", "75887156211589")
                        .withQueryStringParameter("offset", "0")
                        .withQueryStringParameter("max", "1"),
                exactly(1)
        ).respond(
                response().withStatusCode(200).withBody(loadResource("data/links/datalinks_list")).withContentType(MediaType.APPLICATION_JSON)
        );
        // mock fetch data links list
        mock.when(
                request().withMethod("GET").withPath("/data-links")
                        .withQueryStringParameter("workspaceId", "75887156211589")
                        .withQueryStringParameter("search", "a-test-bucket-eend-us-east-1"), exactly(1)
        ).respond(
                response().withStatusCode(200).withBody(loadResource("data/links/datalinks_list")).withContentType(MediaType.APPLICATION_JSON)
        );

        // Create a test file
        Path testFile = tempDir().resolve("test.txt");
        String content = "test content";
        Files.write(testFile, content.getBytes());

        // Mock multipart upload request
        mock.when(
                request()
                        .withMethod("POST").withPath("/data-links/v1-cloud-c2875f38a7b5c8fe34a5b382b5f9e0c4/upload")
                        .withQueryStringParameter("workspaceId", "75887156211589")
                        .withQueryStringParameter("credentialsId", "57Ic6reczFn78H1DTaaXkp"),
                exactly(1)
        ).respond(
                response().withStatusCode(200).withBody("{\n" +
                        "    \"uploadId\": \"upload-123\",\n" +
                        "    \"uploadUrls\": [\"http://localhost:" + mock.getPort() + "/upload\"]\n" +
                        "}").withContentType(MediaType.APPLICATION_JSON)
        );

        // Mock the actual upload
        mock.when(
                request()
                        .withMethod("PUT").withPath("/upload"),
                exactly(1)
        ).respond(
                response()
                        .withStatusCode(200)
                        .withHeader(new Header("Etag", "etag-123"))
        );

        // Mock finish upload request
        mock.when(request()
                .withMethod("POST").withPath("/data-links/v1-cloud-c2875f38a7b5c8fe34a5b382b5f9e0c4/upload/finish")
                .withQueryStringParameter("workspaceId", "75887156211589")
                .withQueryStringParameter("credentialsId", "57Ic6reczFn78H1DTaaXkp")
                .withBody(json("" +
                               "{\n" +
                               "        \"uploadId\":\"upload-123\",\n" +
                               "        \"fileName\":\"test.txt\",\n" +
                               "        \"tags\":[{\"partNumber\":1,\"eTag\":\"etag-123\"}],\n" +
                               "        \"withError\":false\n" +
                               "}\n")),exactly(1)
        ).respond(
                response().withStatusCode(200)
        );

        ExecOut out = exec(format, mock, "data-links", "upload", "-w", "75887156211589", "-n", "a-test-bucket-eend-us-east-1",
                "-c", "57Ic6reczFn78H1DTaaXkp", testFile.toString());

        assertOutput(format, out, DataLinkFileTransferResult.uploaded(List.of(
                new DataLinkFileTransferResult.SimplePathInfo(DataLinkItemType.FILE, testFile.toString(), 1)
        )));

        // No errors thrown
        assertEquals("", out.stdErr);
        assertEquals(0, out.exitCode);

        Files.deleteIfExists(testFile);
    }

    @ParameterizedTest
    @EnumSource(value = OutputType.class, names = {"json"})
    void testUploadSingleFileFailsButStillFinalizesUpload(OutputType format, MockServerClient mock) throws IOException {
        // credentials fetch
        mock.when(
                request().withMethod("GET").withPath("/credentials").withQueryStringParameter("workspaceId", "75887156211589"), exactly(1)
        ).respond(
                response().withStatusCode(200).withBody("{\"credentials\":[{\"id\":\"57Ic6reczFn78H1DTaaXkp\",\"name\":\"aws\",\"description\":null,\"discriminator\":\"aws\",\"baseUrl\":null,\"category\":null,\"deleted\":null,\"lastUsed\":\"2021-09-09T07:20:53Z\",\"dateCreated\":\"2021-09-08T05:48:51Z\",\"lastUpdated\":\"2021-09-08T05:48:51Z\"}]}").withContentType(MediaType.APPLICATION_JSON)
        );

        // status check
        mock.when(
                request()
                        .withMethod("GET").withPath("/data-links")
                        .withQueryStringParameter("workspaceId", "75887156211589")
                        .withQueryStringParameter("offset", "0")
                        .withQueryStringParameter("max", "1"),
                exactly(1)
        ).respond(
                response().withStatusCode(200).withBody(loadResource("data/links/datalinks_list")).withContentType(MediaType.APPLICATION_JSON)
        );
        // mock fetch data links list
        mock.when(
                request().withMethod("GET").withPath("/data-links")
                        .withQueryStringParameter("workspaceId", "75887156211589")
                        .withQueryStringParameter("search", "a-test-bucket-eend-us-east-1"), exactly(1)
        ).respond(
                response().withStatusCode(200).withBody(loadResource("data/links/datalinks_list")).withContentType(MediaType.APPLICATION_JSON)
        );

        // Create a test file
        Path testFile = tempDir().resolve("test.txt");
        String content = "test content";
        Files.write(testFile, content.getBytes());

        // Mock multipart upload request
        mock.when(
                request()
                        .withMethod("POST").withPath("/data-links/v1-cloud-c2875f38a7b5c8fe34a5b382b5f9e0c4/upload")
                        .withQueryStringParameter("workspaceId", "75887156211589")
                        .withQueryStringParameter("credentialsId", "57Ic6reczFn78H1DTaaXkp"),
                exactly(1)
        ).respond(
                response().withStatusCode(200).withBody("{\n" +
                                                        "    \"uploadId\": \"upload-123\",\n" +
                                                        "    \"uploadUrls\": [\"http://localhost:" + mock.getPort() + "/upload\"]\n" +
                                                        "}").withContentType(MediaType.APPLICATION_JSON)
        );

        // Mock the actual upload - returns a 404
        mock.when(
                request()
                        .withMethod("PUT").withPath("/upload"),
                exactly(1)
        ).respond(
                response()
                        .withStatusCode(404)
                        .withBody("not found".getBytes())
        );

        // Mock finish upload request
        mock.when(request()
                .withMethod("POST").withPath("/data-links/v1-cloud-c2875f38a7b5c8fe34a5b382b5f9e0c4/upload/finish")
                .withQueryStringParameter("workspaceId", "75887156211589")
                .withQueryStringParameter("credentialsId", "57Ic6reczFn78H1DTaaXkp")
                .withBody(json("" +
                               "{\n" +
                               "        \"uploadId\":\"upload-123\",\n" +
                               "        \"fileName\":\"test.txt\",\n" +
                               "        \"tags\":[],\n" +
                               "        \"withError\":true\n" +
                               "}\n")),exactly(1)
        ).respond(
                response().withStatusCode(200)
        );

        ExecOut out = exec(format, mock, "data-links", "upload", "-w", "75887156211589", "-n", "a-test-bucket-eend-us-east-1",
                "-c", "57Ic6reczFn78H1DTaaXkp", testFile.toString());

        // verify the upload/finish endpoint has been called with "withError"=true in case of Exception occurring
        mock.verify(request().withMethod("POST").withPath("/data-links/v1-cloud-c2875f38a7b5c8fe34a5b382b5f9e0c4/upload/finish")
                .withBody(json("" +
                               "{\n" +
                               "        \"uploadId\":\"upload-123\",\n" +
                               "        \"fileName\":\"test.txt\",\n" +
                               "        \"tags\":[],\n" +
                               "        \"withError\":true\n" +
                               "}\n"))
                , VerificationTimes.exactly(1));

        assertEquals(errorMessage(out.app, new TowerRuntimeException("Failed to upload file: Failed to upload file: HTTP 404, Message: not found")), out.stdErr);
        assertEquals("", out.stdOut);
        assertEquals(1, out.exitCode);

        Files.deleteIfExists(testFile);
    }

    @ParameterizedTest
    @EnumSource(value = OutputType.class, names = {"json"})
    void testUploadSingleFileWithOutputDir(OutputType format, MockServerClient mock) throws IOException {
        // credentials fetch
        mock.when(
                request().withMethod("GET").withPath("/credentials").withQueryStringParameter("workspaceId", "75887156211589"), exactly(1)
        ).respond(
                response().withStatusCode(200).withBody("{\"credentials\":[{\"id\":\"57Ic6reczFn78H1DTaaXkp\",\"name\":\"aws\",\"description\":null,\"discriminator\":\"aws\",\"baseUrl\":null,\"category\":null,\"deleted\":null,\"lastUsed\":\"2021-09-09T07:20:53Z\",\"dateCreated\":\"2021-09-08T05:48:51Z\",\"lastUpdated\":\"2021-09-08T05:48:51Z\"}]}").withContentType(MediaType.APPLICATION_JSON)
        );

        // status check
        mock.when(
                request()
                        .withMethod("GET").withPath("/data-links")
                        .withQueryStringParameter("workspaceId", "75887156211589")
                        .withQueryStringParameter("offset", "0")
                        .withQueryStringParameter("max", "1"),
                exactly(1)
        ).respond(
                response().withStatusCode(200).withBody(loadResource("data/links/datalinks_list")).withContentType(MediaType.APPLICATION_JSON)
        );
        // mock fetch data links list
        mock.when(
                request().withMethod("GET").withPath("/data-links")
                        .withQueryStringParameter("workspaceId", "75887156211589")
                        .withQueryStringParameter("search", "a-test-bucket-eend-us-east-1"), exactly(1)
        ).respond(
                response().withStatusCode(200).withBody(loadResource("data/links/datalinks_list")).withContentType(MediaType.APPLICATION_JSON)
        );

        // Create a test file
        Path testFile = tempDir().resolve("test.txt");
        String content = "test content";
        Files.write(testFile, content.getBytes());

        // Mock multipart upload request - note the use of upload/{dirPath} endpoint
        mock.when(
                request()
                        .withMethod("POST").withPath("/data-links/v1-cloud-c2875f38a7b5c8fe34a5b382b5f9e0c4/upload/some-dir")
                        .withQueryStringParameter("workspaceId", "75887156211589")
                        .withQueryStringParameter("credentialsId", "57Ic6reczFn78H1DTaaXkp"),
                exactly(1)
        ).respond(
                response().withStatusCode(200).withBody("{\n" +
                        "    \"uploadId\": \"upload-123\",\n" +
                        "    \"uploadUrls\": [\"http://localhost:" + mock.getPort() + "/upload/some-dir\"]\n" +
                        "}").withContentType(MediaType.APPLICATION_JSON)
        );

        // Mock the actual upload
        mock.when(
                request()
                        .withMethod("PUT").withPath("/upload/some-dir"),
                exactly(1)
        ).respond(
                response()
                        .withStatusCode(200)
                        .withHeader(new Header("Etag", "etag-123"))
        );

        // Mock finish upload request - verify the output directory is included in the fileName
        mock.when(request()
                .withMethod("POST").withPath("/data-links/v1-cloud-c2875f38a7b5c8fe34a5b382b5f9e0c4/upload/finish/some-dir")
                .withQueryStringParameter("workspaceId", "75887156211589")
                .withQueryStringParameter("credentialsId", "57Ic6reczFn78H1DTaaXkp")
                .withBody(json("" +
                                "{\n" +
                                "        \"uploadId\":\"upload-123\",\n" +
                                "        \"fileName\":\"test.txt\",\n" +
                                "        \"tags\":[{\"partNumber\":1,\"eTag\":\"etag-123\"}],\n" +
                                "        \"withError\":false\n" +
                                "}\n")),exactly(1)
        ).respond(
                response().withStatusCode(200)
        );

        ExecOut out = exec(format, mock, "data-links", "upload", "-w", "75887156211589", "-n", "a-test-bucket-eend-us-east-1",
                "-c", "57Ic6reczFn78H1DTaaXkp", "-o", "some-dir", testFile.toString());

        assertOutput(format, out, DataLinkFileTransferResult.uploaded(List.of(
                new DataLinkFileTransferResult.SimplePathInfo(DataLinkItemType.FILE, testFile.toString(), 1)
        )));

        // No errors thrown
        assertEquals("", out.stdErr);
        assertEquals(0, out.exitCode);

        Files.deleteIfExists(testFile);
    }

    @ParameterizedTest
    @EnumSource(value = OutputType.class, names = {"json"})
    void testUploadSingleFileToGoogle(OutputType format, MockServerClient mock) throws IOException {
        // credentials fetch
        mock.when(
                request().withMethod("GET").withPath("/credentials").withQueryStringParameter("workspaceId", "75887156211589"), exactly(1)
        ).respond(
                response().withStatusCode(200).withBody("{\"credentials\":[{\"id\":\"google-creds-id\",\"name\":\"google\",\"description\":null,\"discriminator\":\"google\",\"baseUrl\":null,\"category\":null,\"deleted\":null,\"lastUsed\":\"2021-09-09T07:20:53Z\",\"dateCreated\":\"2021-09-08T05:48:51Z\",\"lastUpdated\":\"2021-09-08T05:48:51Z\"}]}").withContentType(MediaType.APPLICATION_JSON)
        );

        // status check
        mock.when(
                request()
                        .withMethod("GET").withPath("/data-links")
                        .withQueryStringParameter("workspaceId", "75887156211589")
                        .withQueryStringParameter("offset", "0")
                        .withQueryStringParameter("max", "1"),
                exactly(1)
        ).respond(
                response().withStatusCode(200).withBody(loadResource("data/links/datalinks_list")).withContentType(MediaType.APPLICATION_JSON)
        );

        // mock fetch data links list
        mock.when(
                request().withMethod("GET").withPath("/data-links")
                        .withQueryStringParameter("workspaceId", "75887156211589")
                        .withQueryStringParameter("search", "google-storage"), exactly(1)
        ).respond(
                response().withStatusCode(200).withBody(json("""
                        {
                          "dataLinks": [
                            {
                              "id": "v1-cloud-google-storage-id",
                              "name": "google-storage",
                              "description": null,
                              "resourceRef": "gs://google-storage",
                              "type": "bucket",
                              "provider": "google",
                              "region": "us-west-2",
                              "credentials": [
                                {
                                  "id": "google-creds-id",
                                  "name": "google",
                                  "provider": "google"
                                }
                              ],
                              "publicAccessible": false,
                              "hidden": false,
                              "status": null,
                              "message": null
                            }
                          ]
                        }
                        """)).withContentType(MediaType.APPLICATION_JSON)
        );

        // Create a test file
        Path testFile = tempDir().resolve("test.txt");
        String content = "test content";
        Files.write(testFile, content.getBytes());

        // Mock multipart upload request
        mock.when(
                request()
                        .withMethod("POST").withPath("/data-links/v1-cloud-google-storage-id/upload")
                        .withQueryStringParameter("workspaceId", "75887156211589")
                        .withQueryStringParameter("credentialsId", "google-creds-id"),
                exactly(1)
        ).respond(
                response().withStatusCode(200).withBody("{\n" +
                        "    \"uploadId\": \"upload-123\",\n" +
                        "    \"uploadUrls\": [\"http://localhost:" + mock.getPort() + "/upload\"]\n" +
                        "}").withContentType(MediaType.APPLICATION_JSON)
        );

        // Mock the actual upload with resumable upload behavior
        mock.when(
                request()
                        .withMethod("PUT")
                        .withPath("/upload")
                        .withHeader("Content-Range", "bytes 0-" + (content.length() - 1) + "/" + content.length()),
                exactly(1)
        ).respond(
                response()
                        .withStatusCode(200)
        );

        ExecOut out = exec(format, mock, "data-links", "upload", "-w", "75887156211589", "-n", "google-storage",
                "-c", "google-creds-id", testFile.toString());

        assertOutput(format, out, DataLinkFileTransferResult.uploaded(List.of(
                new DataLinkFileTransferResult.SimplePathInfo(DataLinkItemType.FILE, testFile.toString(), 1)
        )));

        // No errors thrown
        assertEquals("", out.stdErr);
        assertEquals(0, out.exitCode);

        Files.deleteIfExists(testFile);
    }

    @ParameterizedTest
    @EnumSource(value = OutputType.class, names = {"json"})
    void testUploadSingleFileToAzure(OutputType format, MockServerClient mock) throws IOException {
        // credentials fetch
        mock.when(
                request().withMethod("GET").withPath("/credentials").withQueryStringParameter("workspaceId", "75887156211589"), exactly(1)
        ).respond(
                response().withStatusCode(200).withBody("{\"credentials\":[{\"id\":\"azure-creds-id\",\"name\":\"azure\",\"description\":null,\"discriminator\":\"azure\",\"baseUrl\":null,\"category\":null,\"deleted\":null,\"lastUsed\":\"2021-09-09T07:20:53Z\",\"dateCreated\":\"2021-09-08T05:48:51Z\",\"lastUpdated\":\"2021-09-08T05:48:51Z\"}]}").withContentType(MediaType.APPLICATION_JSON)
        );

        // status check
        mock.when(
                request()
                        .withMethod("GET").withPath("/data-links")
                        .withQueryStringParameter("workspaceId", "75887156211589")
                        .withQueryStringParameter("offset", "0")
                        .withQueryStringParameter("max", "1"),
                exactly(1)
        ).respond(
                response().withStatusCode(200).withBody(loadResource("data/links/datalinks_list")).withContentType(MediaType.APPLICATION_JSON)
        );

        // mock fetch data links list
        mock.when(
                request().withMethod("GET").withPath("/data-links")
                        .withQueryStringParameter("workspaceId", "75887156211589")
                        .withQueryStringParameter("search", "azure-storage"), exactly(1)
        ).respond(
                response().withStatusCode(200).withBody(json("""
                        {
                          "dataLinks": [
                            {
                              "id": "v1-cloud-azurestorage-id",
                              "name": "azure-storage",
                              "description": null,
                              "resourceRef": "az://azure-storage",
                              "type": "bucket",
                              "provider": "azure",
                              "region": "us-west-2",
                              "credentials": [
                                {
                                  "id": "azure-creds-id",
                                  "name": "azure",
                                  "provider": "azure"
                                }
                              ],
                              "publicAccessible": false,
                              "hidden": false,
                              "status": null,
                              "message": null
                            }
                          ]
                        }
                        """)).withContentType(MediaType.APPLICATION_JSON)
        );

        // Create a test file
        Path testFile = tempDir().resolve("test.txt");
        String content = "test content";
        Files.write(testFile, content.getBytes());

        // Mock multipart upload request with block IDs
        mock.when(
                request()
                        .withMethod("POST").withPath("/data-links/v1-cloud-azurestorage-id/upload")
                        .withQueryStringParameter("workspaceId", "75887156211589")
                        .withQueryStringParameter("credentialsId", "azure-creds-id"),
                exactly(1)
        ).respond(
                response().withStatusCode(200).withBody("{\n" +
                        "    \"uploadId\": \"upload-123\",\n" +
                        "    \"uploadUrls\": [\"http://localhost:" + mock.getPort() + "/upload?blockid=block1&comp=block\"]\n" +
                        "}").withContentType(MediaType.APPLICATION_JSON)
        );

        // Mock the block upload
        mock.when(
                request()
                        .withMethod("PUT")
                        .withPath("/upload")
                        .withQueryStringParameter("blockid", "block1")
                        .withQueryStringParameter("comp", "block"),
                exactly(1)
        ).respond(
                response()
                        .withStatusCode(201)
        );

        // Mock the block list finalization
        mock.when(
                request()
                        .withMethod("PUT")
                        .withPath("/upload")
                        .withQueryStringParameter("comp", "blocklist")
                        .withBody("<?xml version=\"1.0\" encoding=\"utf-8\"?><BlockList><Uncommitted>block1</Uncommitted></BlockList>"),
                exactly(1)
        ).respond(
                response()
                        .withStatusCode(201)
        );

        ExecOut out = exec(format, mock, "data-links", "upload", "-w", "75887156211589", "-n", "azure-storage",
                "-c", "azure-creds-id", testFile.toString());

        assertOutput(format, out, DataLinkFileTransferResult.uploaded(List.of(
                new DataLinkFileTransferResult.SimplePathInfo(DataLinkItemType.FILE, testFile.toString(), 1)
        )));

        // No errors thrown
        assertEquals("", out.stdErr);
        assertEquals(0, out.exitCode);

        Files.deleteIfExists(testFile);
    }

    @ParameterizedTest
    @EnumSource(value = OutputType.class, names = {"json"})
    void testUploadTooManyFiles(OutputType format, MockServerClient mock) throws IOException {
        // Create a temporary directory with more than 300 files
        Path tempDirectory = tempDir().resolve("many-files");
        Files.createDirectories(tempDirectory);
        
        // Create 301 files
        for (int i = 0; i < 301; i++) {
            Path file = tempDirectory.resolve("file" + i + ".txt");
            Files.write(file, ("content " + i).getBytes());
        }

        // credentials fetch
        mock.when(
                request().withMethod("GET").withPath("/credentials").withQueryStringParameter("workspaceId", "75887156211589"), exactly(1)
        ).respond(
                response().withStatusCode(200).withBody("{\"credentials\":[{\"id\":\"aws-creds-id\",\"name\":\"aws\",\"description\":null,\"discriminator\":\"aws\",\"baseUrl\":null,\"category\":null,\"deleted\":null,\"lastUsed\":\"2021-09-09T07:20:53Z\",\"dateCreated\":\"2021-09-08T05:48:51Z\",\"lastUpdated\":\"2021-09-08T05:48:51Z\"}]}").withContentType(MediaType.APPLICATION_JSON)
        );

        ExecOut out = exec(format, mock, "data-links", "upload", "-w", "75887156211589", "-n", "aws-storage",
                "-c", "aws-creds-id", tempDirectory.toString());

        // Verify error message
        assertEquals(errorMessage(out.app, new TowerRuntimeException("Cannot upload more than 300 files at once. Found at least 301 files at provided paths. Please reduce number of files to upload in single batch to 300.")), out.stdErr);
        assertEquals("", out.stdOut);
        assertEquals(1, out.exitCode);

        // Cleanup
        deleteDirectory(tempDirectory);
    }

    private void deleteDirectory(Path directory) throws IOException {
        if (Files.exists(directory)) {
            Files.walk(directory)
                    .sorted((a, b) -> b.compareTo(a))
                    .forEach(path -> {
                        try {
                            Files.deleteIfExists(path);
                        } catch (IOException e) {
                            throw new UncheckedIOException(e);
                        }
                    });
        }
    }
}
