name: Lint Markdown
on: [push, pull_request]

jobs:
  Markdown:
    permissions:
      contents: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # ratchet:actions/checkout@v2

      - uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # ratchet:actions/setup-node@v2

      - name: Install markdownlint
        run: npm install -g markdownlint-cli

      - name: Run Markdownlint
        run: markdownlint .