name: Generate dependency graph for tower-cli
on:
  push:
    branches: ['master']


permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: graalvm/setup-graalvm@v1
      with:
        java-version: '21'
        distribution: 'graalvm'
        components: 'native-image'
        native-image-musl: 'true'


    - name: Generate and submit dependency graph for tower-cli
      uses: gradle/actions/dependency-submission@v4
      with:
        dependency-resolution-task: ":dependencies"
        additional-arguments: "--configuration runtimeClasspath"
        dependency-graph: generate-and-submit
